### ISSUE TITLE
Working perfectly on Python 3.5.4

### ISSUE THREAD

**Issue by staticdev** [celiao/tmdbsimple#47]
I couldn't test all methods, but the one's related to movies (no tests for tv shows or series) were extensively tested with no problems.

How are you running these unit tests? Maybe I can run them too.

**Comment by celiao** [comment]
@staticdev,

I presume you ran your movie tests on `tmdbsimple 2.1.0`?

You can run the unit tests with:

```
cd <working parent directory>
source <your virtualenv environment>         # if desired
pip3 install requests                        # if necessary for your virtualenv
git clone https://github.com/celiao/tmdbsimple.git
cd tmdbsimple
mv tests/keys.py.TEMPLATE tests/keys.py
vim tests/keys.py                            # or your favorite editor, add your private keys
python -m unittest discover tests            # to run all the tests, an auth token test may fail
python -m unittest tests.test_movies         # to run a specific set of tests
```

Good luck.

**Comment by staticdev** [comment]
My test results - I only added my API key. Is the other fields in keys.py required? I don't need any of them in the application I am using.

python -m unittest discover tests
EEEEEEEEEE.E.E.......................E...........E.................................E................E.....
======================================================================
ERROR: test_account_favorite (test_account.AccountTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/app/tmdbsimple/tests/test_account.py", line 74, in test_account_favorite
    response = acct.info() # to set acct.id
  File "/app/tmdbsimple/tmdbsimple/account.py", line 55, in info
    response = self._GET(path, kwargs)
  File "/app/tmdbsimple/tmdbsimple/base.py", line 85, in _GET
    return self._request('GET', path, params=params)
  File "/app/tmdbsimple/tmdbsimple/base.py", line 80, in _request
    response.raise_for_status()
  File "/usr/local/lib/python3.5/site-packages/requests/models.py", line 935, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: https://api.themoviedb.org/3/account?api_key=MY_API_KEY&session_id=

======================================================================
ERROR: test_account_favorite_movies (test_account.AccountTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/app/tmdbsimple/tests/test_account.py", line 60, in test_account_favorite_movies
    response = acct.info() # to set acct.id
  File "/app/tmdbsimple/tmdbsimple/account.py", line 55, in info
    response = self._GET(path, kwargs)
  File "/app/tmdbsimple/tmdbsimple/base.py", line 85, in _GET
    return self._request('GET', path, params=params)
  File "/app/tmdbsimple/tmdbsimple/base.py", line 80, in _request
    response.raise_for_status()
  File "/usr/local/lib/python3.5/site-packages/requests/models.py", line 935, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: https://api.themoviedb.org/3/account?api_key=MY_API_KEY&session_id=

======================================================================
ERROR: test_account_favorite_tv (test_account.AccountTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/app/tmdbsimple/tests/test_account.py", line 67, in test_account_favorite_tv
    response = acct.info() # to set acct.id
  File "/app/tmdbsimple/tmdbsimple/account.py", line 55, in info
    response = self._GET(path, kwargs)
  File "/app/tmdbsimple/tmdbsimple/base.py", line 85, in _GET
    return self._request('GET', path, params=params)
  File "/app/tmdbsimple/tmdbsimple/base.py", line 80, in _request
    response.raise_for_status()
  File "/usr/local/lib/python3.5/site-packages/requests/models.py", line 935, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: https://api.themoviedb.org/3/account?api_key=MY_API_KEY&session_id=

======================================================================
ERROR: test_account_info (test_account.AccountTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/app/tmdbsimple/tests/test_account.py", line 48, in test_account_info
    response = acct.info()
  File "/app/tmdbsimple/tmdbsimple/account.py", line 55, in info
    response = self._GET(path, kwargs)
  File "/app/tmdbsimple/tmdbsimple/base.py", line 85, in _GET
    return self._request('GET', path, params=params)
  File "/app/tmdbsimple/tmdbsimple/base.py", line 80, in _request
    response.raise_for_status()
  File "/usr/local/lib/python3.5/site-packages/requests/models.py", line 935, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: https://api.themoviedb.org/3/account?api_key=MY_API_KEY&session_id=

======================================================================
ERROR: test_account_lists (test_account.AccountTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/app/tmdbsimple/tests/test_account.py", line 53, in test_account_lists
    response = acct.info() # to set acct.id
  File "/app/tmdbsimple/tmdbsimple/account.py", line 55, in info
    response = self._GET(path, kwargs)
  File "/app/tmdbsimple/tmdbsimple/base.py", line 85, in _GET
    return self._request('GET', path, params=params)
  File "/app/tmdbsimple/tmdbsimple/base.py", line 80, in _request
    response.raise_for_status()
  File "/usr/local/lib/python3.5/site-packages/requests/models.py", line 935, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: https://api.themoviedb.org/3/account?api_key=MY_API_KEY&session_id=

======================================================================
ERROR: test_account_rated_movies (test_account.AccountTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/app/tmdbsimple/tests/test_account.py", line 85, in test_account_rated_movies
    response = acct.info() # to set acct.id
  File "/app/tmdbsimple/tmdbsimple/account.py", line 55, in info
    response = self._GET(path, kwargs)
  File "/app/tmdbsimple/tmdbsimple/base.py", line 85, in _GET
    return self._request('GET', path, params=params)
  File "/app/tmdbsimple/tmdbsimple/base.py", line 80, in _request
    response.raise_for_status()
  File "/usr/local/lib/python3.5/site-packages/requests/models.py", line 935, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: https://api.themoviedb.org/3/account?api_key=MY_API_KEY&session_id=

======================================================================
ERROR: test_account_rated_tv (test_account.AccountTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/app/tmdbsimple/tests/test_account.py", line 92, in test_account_rated_tv
    response = acct.info() # to set acct.id
  File "/app/tmdbsimple/tmdbsimple/account.py", line 55, in info
    response = self._GET(path, kwargs)
  File "/app/tmdbsimple/tmdbsimple/base.py", line 85, in _GET
    return self._request('GET', path, params=params)
  File "/app/tmdbsimple/tmdbsimple/base.py", line 80, in _request
    response.raise_for_status()
  File "/usr/local/lib/python3.5/site-packages/requests/models.py", line 935, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: https://api.themoviedb.org/3/account?api_key=MY_API_KEY&session_id=

======================================================================
ERROR: test_account_watchlist (test_account.AccountTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/app/tmdbsimple/tests/test_account.py", line 116, in test_account_watchlist
    response = acct.info() # to set acct.id
  File "/app/tmdbsimple/tmdbsimple/account.py", line 55, in info
    response = self._GET(path, kwargs)
  File "/app/tmdbsimple/tmdbsimple/base.py", line 85, in _GET
    return self._request('GET', path, params=params)
  File "/app/tmdbsimple/tmdbsimple/base.py", line 80, in _request
    response.raise_for_status()
  File "/usr/local/lib/python3.5/site-packages/requests/models.py", line 935, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: https://api.themoviedb.org/3/account?api_key=MY_API_KEY&session_id=

======================================================================
ERROR: test_account_watchlist_movies (test_account.AccountTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/app/tmdbsimple/tests/test_account.py", line 100, in test_account_watchlist_movies
    response = acct.info() # to set acct.id
  File "/app/tmdbsimple/tmdbsimple/account.py", line 55, in info
    response = self._GET(path, kwargs)
  File "/app/tmdbsimple/tmdbsimple/base.py", line 85, in _GET
    return self._request('GET', path, params=params)
  File "/app/tmdbsimple/tmdbsimple/base.py", line 80, in _request
    response.raise_for_status()
  File "/usr/local/lib/python3.5/site-packages/requests/models.py", line 935, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: https://api.themoviedb.org/3/account?api_key=MY_API_KEY&session_id=

======================================================================
ERROR: test_account_watchlist_tv (test_account.AccountTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/app/tmdbsimple/tests/test_account.py", line 108, in test_account_watchlist_tv
    response = acct.info() # to set acct.id
  File "/app/tmdbsimple/tmdbsimple/account.py", line 55, in info
    response = self._GET(path, kwargs)
  File "/app/tmdbsimple/tmdbsimple/base.py", line 85, in _GET
    return self._request('GET', path, params=params)
  File "/app/tmdbsimple/tmdbsimple/base.py", line 80, in _request
    response.raise_for_status()
  File "/usr/local/lib/python3.5/site-packages/requests/models.py", line 935, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: https://api.themoviedb.org/3/account?api_key=MY_API_KEY&session_id=

======================================================================
ERROR: test_authentication_token_new (test_account.AuthenticationTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/app/tmdbsimple/tests/test_account.py", line 142, in test_authentication_token_new
    response = auth.token_validate_with_login(**kwargs)
  File "/app/tmdbsimple/tmdbsimple/account.py", line 294, in token_validate_with_login
    response = self._GET(path, kwargs)
  File "/app/tmdbsimple/tmdbsimple/base.py", line 85, in _GET
    return self._request('GET', path, params=params)
  File "/app/tmdbsimple/tmdbsimple/base.py", line 80, in _request
    response.raise_for_status()
  File "/usr/local/lib/python3.5/site-packages/requests/models.py", line 935, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://api.themoviedb.org/3/authentication/token/validate_with_login?password=&api_key=MY_API_KEY&username=&request_token=25cce1229e189690039d539ac2c8372cd07223cd

======================================================================
ERROR: test_lists_create_add_remove_clear_delete (test_account.ListsTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/app/tmdbsimple/tests/test_account.py", line 196, in test_lists_create_add_remove_clear_delete
    response = lst.create_list(**kwargs)
  File "/app/tmdbsimple/tmdbsimple/account.py", line 439, in create_list
    response = self._POST(path, kwargs, payload)
  File "/app/tmdbsimple/tmdbsimple/base.py", line 88, in _POST
    return self._request('POST', path, params=params, payload=payload)
  File "/app/tmdbsimple/tmdbsimple/base.py", line 80, in _request
    response.raise_for_status()
  File "/usr/local/lib/python3.5/site-packages/requests/models.py", line 935, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: https://api.themoviedb.org/3/list?session_id=&api_key=MY_API_KEY

======================================================================
ERROR: test_movies_account_states (test_movies.MoviesTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/app/tmdbsimple/tests/test_movies.py", line 164, in test_movies_account_states
    response = movie.account_states(session_id=SESSION_ID)
  File "/app/tmdbsimple/tmdbsimple/movies.py", line 393, in account_states
    response = self._GET(path, kwargs)
  File "/app/tmdbsimple/tmdbsimple/base.py", line 85, in _GET
    return self._request('GET', path, params=params)
  File "/app/tmdbsimple/tmdbsimple/base.py", line 80, in _request
    response.raise_for_status()
  File "/usr/local/lib/python3.5/site-packages/requests/models.py", line 935, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: https://api.themoviedb.org/3/movie/550/account_states?api_key=MY_API_KEY&session_id=

======================================================================
ERROR: test_movies_rating (test_movies.MoviesTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/app/tmdbsimple/tests/test_movies.py", line 171, in test_movies_rating
    response = movie.rating(session_id=SESSION_ID, value=RATING)
  File "/app/tmdbsimple/tmdbsimple/movies.py", line 416, in rating
    response = self._POST(path, kwargs, payload)
  File "/app/tmdbsimple/tmdbsimple/base.py", line 88, in _POST
    return self._request('POST', path, params=params, payload=payload)
  File "/app/tmdbsimple/tmdbsimple/base.py", line 80, in _request
    response.raise_for_status()
  File "/usr/local/lib/python3.5/site-packages/requests/models.py", line 935, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: https://api.themoviedb.org/3/movie/103332/rating?api_key=MY_API_KEY&session_id=

======================================================================
ERROR: test_tv_episodes_rating (test_tv.TVEpisodesTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/app/tmdbsimple/tests/test_tv.py", line 222, in test_tv_episodes_rating
    response = tv_episodes.rating(session_id=SESSION_ID, value=RATING)
  File "/app/tmdbsimple/tmdbsimple/tv.py", line 546, in rating
    response = self._POST(path, kwargs, payload)
  File "/app/tmdbsimple/tmdbsimple/base.py", line 88, in _POST
    return self._request('POST', path, params=params, payload=payload)
  File "/app/tmdbsimple/tmdbsimple/base.py", line 80, in _request
    response.raise_for_status()
  File "/usr/local/lib/python3.5/site-packages/requests/models.py", line 935, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: https://api.themoviedb.org/3/tv/1396/season/1/episode/1/rating?api_key=MY_API_KEY&session_id=

======================================================================
ERROR: test_tv_rating (test_tv.TVTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/app/tmdbsimple/tests/test_tv.py", line 88, in test_tv_rating
    response = tv.rating(session_id=SESSION_ID, value=RATING)
  File "/app/tmdbsimple/tmdbsimple/tv.py", line 173, in rating
    response = self._POST(path, kwargs, payload)
  File "/app/tmdbsimple/tmdbsimple/base.py", line 88, in _POST
    return self._request('POST', path, params=params, payload=payload)
  File "/app/tmdbsimple/tmdbsimple/base.py", line 80, in _request
    response.raise_for_status()
  File "/usr/local/lib/python3.5/site-packages/requests/models.py", line 935, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: https://api.themoviedb.org/3/tv/1396/rating?api_key=MY_API_KEY&session_id=

----------------------------------------------------------------------
Ran 106 tests in 68.993s

FAILED (errors=16)

**Comment by celiao** [comment]
To eliminate those errors, you need to set the SESSION_ID also.  It's not that hard to get a session id, if you follow the instructions on the TMDB API web page regarding [Authentication](https://developers.themoviedb.org/3/authentication/how-do-i-generate-a-session-id).

**Comment by staticdev** [comment]
python -m unittest discover tests
FFEF...FFE.E.....................................F.................................F................F.....
======================================================================
ERROR: test_account_favorite_tv (test_account.AccountTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/app/tmdbsimple/tests/test_account.py", line 69, in test_account_favorite_tv
    self.assertEqual(acct.results[0]['name'], tvtitle)
IndexError: list index out of range

======================================================================
ERROR: test_account_watchlist_tv (test_account.AccountTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/app/tmdbsimple/tests/test_account.py", line 111, in test_account_watchlist_tv
    self.assertEqual(acct.results[0]['name'], tvtitle)
IndexError: list index out of range

======================================================================
ERROR: test_authentication_token_new (test_account.AuthenticationTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/app/tmdbsimple/tests/test_account.py", line 142, in test_authentication_token_new
    response = auth.token_validate_with_login(**kwargs)
  File "/app/tmdbsimple/tmdbsimple/account.py", line 294, in token_validate_with_login
    response = self._GET(path, kwargs)
  File "/app/tmdbsimple/tmdbsimple/base.py", line 85, in _GET
    return self._request('GET', path, params=params)
  File "/app/tmdbsimple/tmdbsimple/base.py", line 80, in _request
    response.raise_for_status()
  File "/usr/local/lib/python3.5/site-packages/requests/models.py", line 935, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://api.themoviedb.org/3/authentication/token/validate_with_login?username=&api_key=MY_API_KEY&password=&request_token=25efb79a89fa73ff4b426c6000a4badb7bac6668

======================================================================
FAIL: test_account_favorite (test_account.AccountTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/app/tmdbsimple/tests/test_account.py", line 81, in test_account_favorite
    self.assertEqual(acct.status_code, status_code)
AssertionError: 1 != 12

======================================================================
FAIL: test_account_favorite_movies (test_account.AccountTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/app/tmdbsimple/tests/test_account.py", line 62, in test_account_favorite_movies
    self.assertEqual(acct.results[0]['title'], movietitle)
AssertionError: 'Monsters University' != 'The Brother from Another Planet'
- Monsters University
+ The Brother from Another Planet


======================================================================
FAIL: test_account_info (test_account.AccountTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/app/tmdbsimple/tests/test_account.py", line 49, in test_account_info
    self.assertEqual(acct.username, username)
AssertionError: 'MY_USERNAME' != ''
- MY_USERNAME
+ 


======================================================================
FAIL: test_account_watchlist (test_account.AccountTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/app/tmdbsimple/tests/test_account.py", line 123, in test_account_watchlist
    self.assertEqual(acct.status_code, status_code)
AssertionError: 1 != 12

======================================================================
FAIL: test_account_watchlist_movies (test_account.AccountTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/app/tmdbsimple/tests/test_account.py", line 103, in test_account_watchlist_movies
    self.assertEqual(acct.results[0]['title'], movietitle)
AssertionError: 'Star Wars' != 'The Brother from Another Planet'
- Star Wars
+ The Brother from Another Planet


======================================================================
FAIL: test_movies_rating (test_movies.MoviesTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/app/tmdbsimple/tests/test_movies.py", line 172, in test_movies_rating
    self.assertEqual(movie.status_code, status_code)
AssertionError: 1 != 12

======================================================================
FAIL: test_tv_episodes_rating (test_tv.TVEpisodesTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/app/tmdbsimple/tests/test_tv.py", line 223, in test_tv_episodes_rating
    self.assertEqual(tv_episodes.status_code, status_code)
AssertionError: 1 != 12

======================================================================
FAIL: test_tv_rating (test_tv.TVTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/app/tmdbsimple/tests/test_tv.py", line 89, in test_tv_rating
    self.assertEqual(tv.status_code, status_code)
AssertionError: 1 != 12

----------------------------------------------------------------------
Ran 106 tests in 75.342s

FAILED (failures=8, errors=3)

There are the results after creating a session_id for the user MY_USERNAME.
